- id: '1778630464831'
  alias: Streat Light - Off
  description: Automation to turn off Street Light daily
  triggers:
  - trigger: sun
    event: sunrise
    offset: -05:00:00
  conditions: []
  actions:
  - action: switch.turn_off
    metadata: {}
    data: {}
    target:
      device_id: 38dbc885ee27b8f23e0e3a8b55fa5a17
  mode: single
- id: '1778630823884'
  alias: Street Light - On
  description: Automation to turn Street Light On
  triggers:
  - trigger: sun
    event: sunset
    offset: 00:20:00
  conditions: []
  actions:
  - action: switch.turn_on
    metadata: {}
    target:
      device_id: 38dbc885ee27b8f23e0e3a8b55fa5a17
    data: {}
  mode: single
- id: '1778631022999'
  alias: Travel Light - On
  description: ''
  triggers:
  - trigger: sun
    event: sunset
    offset: -00:30:00
  conditions: []
  actions:
  - action: light.turn_on
    metadata: {}
    target:
      entity_id: light.outlet_switch
    data:
      brightness_pct: 100
  mode: single
- id: '1778710577647'
  alias: HVAC Overuse Guard
  description: ''
  triggers:
  - value_template: "{% set room = state_attr(hvac_id, \"current_temperature\") |
      float(none) %}     {% set setpoint = state_attr(hvac_id, \"temperature\") |
      float(none) %}  {% if setpoint is none -%}\n  {%set setpoint = state_attr(hvac_id,
      \"target_temp_high\") | float(none) %}\n{% endif -%}  {{ setpoint is not none
      and room is not none and room > setpoint }}\n"
    variables:
      hvac_id: climate.hallway
      sensor_id: sensor.main_temperature
    for:
      hours: 3
    trigger: template
  conditions: []
  actions:
  - variables:
      hvac_id: climate.hallway
      delta: 3
      fan: 'on'
      fan_hours: 1
      current_setpoint: "{% set t = state_attr(hvac_id, 'temperature') %} {% set t_high
        = state_attr(hvac_id, 'target_temp_high') %} {{ (t if t is not none else t_high)
        | float(0) }}        \n"
      previous_mode: '{{ states(hvac_id) }}'
  - condition: template
    value_template: '{{ current_setpoint > 0 }}'
  - alias: Raise the HVAC setpoint
    action: climate.set_preset_mode
    target:
      entity_id: climate.hallway
    data:
      preset_mode: eco
  - alias: Switch to fan mode
    target:
      entity_id: '{{ hvac_id }}'
    data:
      fan_mode: 'on'
    action: climate.set_fan_mode
  - alias: Run fan for configured duration
    delay:
      seconds: 5
  - alias: Stop fan mode
    target:
      entity_id: '{{ hvac_id }}'
    data:
      fan_mode: 'off'
    action: climate.set_fan_mode
  - alias: Restore previous HVAC mode
    action: climate.set_preset_mode
    target:
      entity_id: climate.hallway
    data:
      preset_mode: none
  - action: notify.mobile_app_bermandsey
    metadata: {}
    data:
      message: Test Message
      title: Overuse!
  - action: notify.send_message
    metadata: {}
    target:
      device_id: 0168cfb1711510e055cfa2c57c9c95e2
    data:
      message: test
      title: test
  mode: single
- id: '1778764984374'
  alias: HVAC Overuse Guard
  description: ''
  use_blueprint:
    path: yngpadjuan/hvac-overuse.yaml
    input:
      hvac_entity: climate.hallway
      input_mobile_app: 0168cfb1711510e055cfa2c57c9c95e2
      overuse_threshold: 4
